/**
 * Angular Code Generator
 *
 * Generates Angular TypeScript code from IR schema.
 */

import {
  IRSchema,
  IRModel,
  IRField,
  IRNamespace,
  IROperation,
  TypeRef,
  ScalarKind,
} from "@jira-db/emitter-common";

// ============================================================
// Public API
// ============================================================

/**
 * Generate all Angular files from IR schema
 */
export function generateAngular(schema: IRSchema): GeneratedFiles {
  const modelsContent = generateModels(schema);
  const apiServiceContent = generateApiService(schema);
  const tauriServiceContent = generateTauriService(schema);
  const indexContent = generateIndex();

  return {
    "models.ts": modelsContent,
    "api.service.ts": apiServiceContent,
    "tauri-api.service.ts": tauriServiceContent,
    "index.ts": indexContent,
  };
}

export interface GeneratedFiles {
  [filename: string]: string;
}

// ============================================================
// Models Generator
// ============================================================

function generateModels(schema: IRSchema): string {
  let output = `// Generated by @jira-db/emit-angular - DO NOT EDIT

`;

  for (const model of schema.models) {
    output += generateInterface(model);
    output += "\n";
  }

  return output;
}

function generateInterface(model: IRModel): string {
  let output = "";

  if (model.doc) {
    output += `/** ${model.doc} */\n`;
  }
  output += `export interface ${model.name} {\n`;

  for (const field of model.fields) {
    const tsType = typeRefToTypeScript(field.type);
    const optional = field.optional ? "?" : "";
    output += `  ${field.name}${optional}: ${tsType};\n`;
  }

  output += `}\n`;
  return output;
}

// ============================================================
// API Service Generator (HTTP)
// ============================================================

function generateApiService(schema: IRSchema): string {
  // Collect all types needed for imports
  const importTypes = collectImportTypes(schema);

  let output = `// Generated by @jira-db/emit-angular - DO NOT EDIT

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

import {
${importTypes.map((t) => `  ${t},`).join("\n")}
} from './models';

@Injectable({ providedIn: 'root' })
export class ApiService {
  private baseUrl = '/api';

  constructor(private http: HttpClient) {}

`;

  for (const ns of schema.namespaces) {
    output += `  // ----------------------------------------\n`;
    output += `  // ${ns.name}\n`;
    output += `  // ----------------------------------------\n\n`;

    for (const op of ns.operations) {
      output += generateHttpMethod(ns, op);
    }
  }

  output += `}\n`;
  return output;
}

function generateHttpMethod(ns: IRNamespace, op: IROperation): string {
  const methodName = `${toCamelCase(ns.name)}${capitalize(op.name)}`;
  const endpoint = `/${toKebabCase(ns.name)}.${toKebabCase(op.name)}`;

  let output = "";
  if (op.doc) {
    output += `  /** ${op.doc} */\n`;
  }
  output += `  ${methodName}(request: ${op.requestType}): Observable<${op.responseType}> {\n`;
  output += `    return this.http.post<${op.responseType}>(\`\${this.baseUrl}${endpoint}\`, request);\n`;
  output += `  }\n\n`;

  return output;
}

// ============================================================
// Tauri Service Generator
// ============================================================

function generateTauriService(schema: IRSchema): string {
  const importTypes = collectImportTypes(schema);

  let output = `// Generated by @jira-db/emit-angular - DO NOT EDIT

import { Injectable } from '@angular/core';
import { invoke } from '@tauri-apps/api/core';
import { from, Observable } from 'rxjs';

import {
${importTypes.map((t) => `  ${t},`).join("\n")}
} from './models';

@Injectable({ providedIn: 'root' })
export class TauriApiService {
`;

  for (const ns of schema.namespaces) {
    output += `  // ----------------------------------------\n`;
    output += `  // ${ns.name}\n`;
    output += `  // ----------------------------------------\n\n`;

    for (const op of ns.operations) {
      output += generateTauriMethod(ns, op);
    }
  }

  output += `}\n`;
  return output;
}

function generateTauriMethod(ns: IRNamespace, op: IROperation): string {
  const methodName = `${toCamelCase(ns.name)}${capitalize(op.name)}`;
  const commandName = `${toSnakeCase(ns.name)}_${toSnakeCase(op.name)}`;

  let output = "";
  if (op.doc) {
    output += `  /** ${op.doc} */\n`;
  }
  output += `  ${methodName}(request: ${op.requestType}): Observable<${op.responseType}> {\n`;
  output += `    return from(invoke<${op.responseType}>('${commandName}', { request }));\n`;
  output += `  }\n\n`;

  return output;
}

// ============================================================
// Index Generator
// ============================================================

function generateIndex(): string {
  return `// Generated by @jira-db/emit-angular - DO NOT EDIT

export * from './models';
export * from './api.service';
export * from './tauri-api.service';
`;
}

// ============================================================
// Type Conversion Utilities
// ============================================================

function typeRefToTypeScript(typeRef: TypeRef): string {
  switch (typeRef.kind) {
    case "scalar":
      return scalarToTypeScript(typeRef.scalar!);
    case "model":
      return typeRef.modelName!;
    case "array":
      return `${typeRefToTypeScript(typeRef.elementType!)}[]`;
    default:
      return "unknown";
  }
}

function scalarToTypeScript(scalar: ScalarKind): string {
  const map: Record<ScalarKind, string> = {
    string: "string",
    boolean: "boolean",
    int32: "number",
    int64: "number",
    float32: "number",
    float64: "number",
    utcDateTime: "string", // ISO 8601 string
    unknown: "unknown", // TypeScript unknown type
  };
  return map[scalar] || "string";
}

// ============================================================
// Helper Functions
// ============================================================

function collectImportTypes(schema: IRSchema): string[] {
  const types = new Set<string>();

  for (const ns of schema.namespaces) {
    for (const op of ns.operations) {
      types.add(op.requestType);
      types.add(op.responseType);
    }
  }

  return Array.from(types).sort();
}

// ============================================================
// String Utilities
// ============================================================

function toSnakeCase(str: string): string {
  return str.replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, "");
}

function toKebabCase(str: string): string {
  return str.replace(/([A-Z])/g, "-$1").toLowerCase().replace(/^-/, "");
}

function toCamelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
